name: MicroKits
version: '1.0.0'
main: dev.cattyn.microkits.MicroKits
api-version: '1.20'
authors: [ cattyn ]
website: https://cattyn.dev/

depend: [CommandAPI]

permissions:
  microkits.kitcreator:
    description: Allows to open kit creator
    default: true
  microkits.kit:
    description: Allows to execute kit command
    default: true
  microkits.reload:
    description: Allows to reload plugins config
    default: op